"""empty message

Revision ID: 4e2a1eeacf9d
Revises: e8aeafb1db65
Create Date: 2024-12-31 20:18:53.291069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2a1eeacf9d'
down_revision: Union[str, None] = 'e8aeafb1db65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'created_at')
    # ### end Alembic commands ###
