"""
Таблица с информацией о перелёте имеет внешний ключ,
который ссылается на таблицу с некими характеристиками самолёта,
который осуществляет перелёт

Revision ID: 96955fd79c7a
Revises: 
Create Date: 2024-12-31 19:13:10.074946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96955fd79c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
            sa.Column('aircraft_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('name', sa.String(length=20), nullable=False),
            sa.Column('weight', sa.Integer(), nullable=False),
            sa.Column('length', sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_index(op.f('ix_aircraft_name'), 'aircraft', ['name'], unique=False)
    op.create_table('flight',
            sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('flight_name', sa.String(length=30), nullable=False),
            sa.Column('departure_country', sa.String(length=50), nullable=False),
            sa.Column('departure_city', sa.String(length=50), nullable=False),
            sa.Column('departure_date_time', sa.DateTime(), nullable=False, comment='format -> YYYY-MM-DD HH:MI:SS'),
            sa.Column('arrival_country', sa.String(length=50), nullable=False),
            sa.Column('arrival_city', sa.String(length=50), nullable=False),
            sa.Column('arrival_date_time', sa.DateTime(), nullable=False, comment='format -> YYYY-MM-DD HH:MI:SS'),
            sa.Column('ticket_cost', sa.Integer(), nullable=False),
            sa.Column('data_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('aircraft_characteristics_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['aircraft_characteristics_id'], ['aircraft.aircraft_id'], ),
            sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_index(op.f('ix_flight_flight_name'), 'flight', ['flight_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_flight_name'), table_name='flight')
    op.drop_table('flight')
    op.drop_index(op.f('ix_aircraft_name'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
