"""empty message

Revision ID: c780ca96f2a8
Revises: 82473cd5eae5
Create Date: 2025-01-01 13:44:34.381652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c780ca96f2a8'
down_revision: Union[str, None] = '82473cd5eae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='or updated at',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='or updated at',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
