"""empty message

Revision ID: 2d61a2d1174b
Revises: 2f7c64a69636
Create Date: 2025-01-01 19:34:40.597298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d61a2d1174b'
down_revision: Union[str, None] = '2f7c64a69636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('ticket_cost_in_usd', sa.Integer(), nullable=False))
    op.drop_column('flight', 'ticket_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('ticket_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('flight', 'ticket_cost_in_usd')
    # ### end Alembic commands ###
